/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynuoc;

/**
 *
 * @author Đình
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMenuhead = new javax.swing.JMenuBar();
        MenuQuanLy = new javax.swing.JMenu();
        MItemBan = new javax.swing.JMenuItem();
        MItemDoUong = new javax.swing.JMenuItem();
        MItemTaiKhoan = new javax.swing.JMenuItem();
        MItemDanhmuc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 720));

        MenuQuanLy.setText("Quản lý");

        MItemBan.setText("Bàn");
        MenuQuanLy.add(MItemBan);

        MItemDoUong.setText("Đồ uống");
        MenuQuanLy.add(MItemDoUong);

        MItemTaiKhoan.setText("Tài Khoản");
        MItemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemTaiKhoanActionPerformed(evt);
            }
        });
        MenuQuanLy.add(MItemTaiKhoan);

        MItemDanhmuc.setText("Danh muc");
        MenuQuanLy.add(MItemDanhmuc);

        JMenuhead.add(MenuQuanLy);

        setJMenuBar(JMenuhead);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MItemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MItemTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuhead;
    private javax.swing.JMenuItem MItemBan;
    private javax.swing.JMenuItem MItemDanhmuc;
    private javax.swing.JMenuItem MItemDoUong;
    private javax.swing.JMenuItem MItemTaiKhoan;
    private javax.swing.JMenu MenuQuanLy;
    // End of variables declaration//GEN-END:variables
}
